# Meta Data for SEO

## Homepage
title = "YERP!"
titleSeparator = "-"
titleAddition = "Your Emergency Response Platform"
description = "YERP is a modular and adaptable approach to monitoring spaces such as bathrooms for potential medical emergencies, while promoting autonomy and preserving privacy."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "flufftronix"
twitterCreator = "flufftronix"
facebookAuthor = "flufftronix"
facebookPublisher = "flufftronix"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/flufftronix"
schemaGitHub = "https://github.com/flufftronix"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/flufftronix/yerp-io"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
